USE [Clarkson's Farm Activities2]
GO

DROP TABLE TestRunTables
DROP TABLE TestRunViews
DROP TABLE TestTables
DROP TABLE TestViews
DROP TABLE TestRuns
DROP TABLE Tables
DROP TABLE Views
DROP TABLE Tests



CREATE TABLE TestRuns(
	TestRunID INT,
	TestDescription VARCHAR(MAX),
	StartAt DATETIME,
	EndAt DATETIME,
	CONSTRAINT PK_TestRuns PRIMARY KEY (TestRunID)
);

CREATE TABLE Tables(
	TableID INT,
	Name VARCHAR(MAX),
	CONSTRAINT PK_Tables PRIMARY KEY (TableID)
)

CREATE TABLE Views(
	ViewID INT,
	Name VARCHAR(MAX),
	CONSTRAINT PK_Views PRIMARY KEY (ViewID)
);

CREATE TABLE Tests(
	TestID INT,
	Name VARCHAR(MAX),
	CONSTRAINT PK_Tests PRIMARY KEY(TestID)
);

CREATE TABLE TestTables(
	TestID INT,
	TableID INT,
	NrRows INT,
	Positions INT,
	CONSTRAINT FK_TestID_TestTables FOREIGN KEY (TestID) REFERENCES Tests (TestID)
	ON DELETE CASCADE
	ON UPDATE CASCADE,
	CONSTRAINT FK_TableID_TestTables FOREIGN KEY (TableID) REFERENCES Tables (TableID)
	ON DELETE CASCADE
	ON UPDATE CASCADE,
	CONSTRAINT PK_TestTables PRIMARY KEY (TestID, TableID) 
);

CREATE TABLE TestViews(
	TestID INT,
	ViewID INT,
	CONSTRAINT FK_TestID_TestViews FOREIGN KEY (TestID) REFERENCES Tests (TestID)
	ON DELETE CASCADE
	ON UPDATE CASCADE,
	CONSTRAINT FK_ViewID_TestTViews FOREIGN KEY (ViewID) REFERENCES Views (ViewID)
	ON DELETE CASCADE
	ON UPDATE CASCADE,
	CONSTRAINT PK_TestViews PRIMARY KEY (TestID, ViewID)
);

CREATE TABLE TestRunTables(
	TestRunID INT,
	TableID INT,
	StartAt DATETIME,
	EndAt DATETIME,
	CONSTRAINT FK_TestRunID_TestRunTables FOREIGN KEY (TestRunID) REFERENCES TestRuns(TestRunID)
	ON DELETE CASCADE
	ON UPDATE CASCADE,
	CONSTRAINT FK_TableID_TestRunTables FOREIGN KEY (TableId) REFERENCES Tables(TableID)
	ON DELETE CASCADE
	ON UPDATE CASCADE,
	CONSTRAINT PK_TestRunTables PRIMARY KEY (TestRunID, TableID)
);

CREATE TABLE TestRunViews(
	TestRunID INT,
	ViewID INT,
	StartAt DATETIME,
	EmdAt DATETIME,
	CONSTRAINT FK_TestRunID_TestRunViews FOREIGN KEY (TestRunID) REFERENCES TestRuns(TestRunID)
	ON DELETE CASCADE
	ON UPDATE CASCADE,
	CONSTRAInT FK_ViewID_TestRunViews FOREIGN KEY (ViewID) REFERENCES Views(ViewID)
	ON DELETE CASCADE
	ON UPDATE CASCADE,
	CONSTRAINT PK_TestRunViews PRIMARY KEY (TestRunID, ViewID)
);